services:
  # PHP Server
  exercise_php:
    container_name: exercise_php
    build:
      context: .
      dockerfile: ./.docker/php/DockerFile
      args:
        PUBLIC_PATH: ${PUBLIC_PATH}
    restart: ${DOCKER_RESTART}
    tty: true
    working_dir: /var/www
    volumes:
      - ${PUBLIC_PATH}:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./.docker/php/out/:/usr/out/

  # Nginx Server
  exercise_nginx:
    container_name: exercise_nginx
    build:
      dockerfile: ./.docker/nginx/DockerFile
    tty: true
    restart: ${DOCKER_RESTART}
    ports:
      - ${NGINX_OUT_PORT}:80
      - ${NGINX_SSL_PORT}:443
    volumes:
      - ${PUBLIC_PATH}:/var/www
      - ./.docker/nginx/app.conf:/etc/nginx/templates/app.conf.template
      - ${CERT_PATH}:/etc/cert/
      - ./.docker/nginx/out/:/usr/out/
    environment:
      - NGINX_HOST=${DOMAIN_NAME}

  # Mysql Server
  exercise_mysql:
    container_name: exercise_mysql
    image: mysql:8.0
    tty: true
    restart: ${DOCKER_RESTART}
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - dbdata:/var/lib/mysql/
      - ./.docker/mysql/local.cnf:/etc/mysql/local.cnf
      - ./.docker/mysql/scripts/:/usr/scripts/
      - ./.docker/mysql/init/:/docker-entrypoint-initdb.d/

  # Phpmyadmin server
  exercise_pma:
    container_name: exercise_pma
    image: phpmyadmin:5.1.3
    restart: ${DOCKER_RESTART}
    environment:
      PMA_HOST: "exercise_mysql"
    ports:
      - ${PMA_PORT}:80

volumes:
  dbdata:
    driver: local
